/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fahmi.penerbangan.form;

import fahmi.penerbangan.model.Penerbangan;
import fahmi.penerbangan.model.Pesawat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fahmi
 */
public class CariPesawatForm extends javax.swing.JFrame {
//    KODING KU
    Pesawat pesawat = new Pesawat();
    PenerbanganForm penerbanganform;
    
    public void tampilData(){
        ArrayList<Pesawat> list = pesawat.read();
        
        DefaultTableModel tableModel = (DefaultTableModel) tbPesawat.getModel();
        tableModel.setRowCount(0);
        
        Object[] row = new Object[3];
        
        for (int i = 0; i<list.size(); i++){
            row[0] = list.get(i).getNo_pesawat();
            row[1] = list.get(i).getNama_pesawat();
            row[2] = list.get(i).getMaskapai();

            tableModel.addRow(row);
        }
    }
    
    public void tampilCari(){
        ArrayList<Pesawat> list = pesawat.search(cariTF.getText());
        
        DefaultTableModel tableModel = (DefaultTableModel) tbPesawat.getModel();
        tableModel.setRowCount(0);
        
        Object[] row = new Object[3];
        
        if(list.size() > 0){
//            System.out.println("Jalan");
            for (int i = 0; i<list.size(); i++){
                row[0] = list.get(i).getNo_pesawat();
                row[1] = list.get(i).getNama_pesawat();
                row[2] = list.get(i).getMaskapai();
                
                tableModel.addRow(row);
            }
        }
    }
    
    /**
     * Creates new form CariPesawatForm
     */
    public CariPesawatForm() {
        initComponents();
        tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPesawat = new javax.swing.JTable();
        cariTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        BTkeluar = new javax.swing.JButton();
        btPesawat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Daftar Pesawat");

        tbPesawat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No Pesawat", "Nama Pesawat", "Maskapai"
            }
        ));
        tbPesawat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPesawatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPesawat);

        cariTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cariTFKeyTyped(evt);
            }
        });

        jLabel7.setText("Cari Berdasarkan Nama / Maskapai/ No");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(31, 31, 31)
                        .addComponent(cariTF, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cariTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BTkeluar.setText("Keluar");
        BTkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTkeluarActionPerformed(evt);
            }
        });

        btPesawat.setText("Pengaturan");
        btPesawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesawatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addComponent(btPesawat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTkeluar)
                .addGap(42, 42, 42))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(326, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTkeluar)
                    .addComponent(btPesawat))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(45, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cariTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariTFKeyTyped
        tampilCari();
    }//GEN-LAST:event_cariTFKeyTyped

    private void BTkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTkeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BTkeluarActionPerformed

    private void tbPesawatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPesawatMouseClicked

        penerbanganform.setNo_pesawat(tbPesawat.getValueAt(tbPesawat.getSelectedRow(), 0).toString());
        penerbanganform.setNama_pesawat(tbPesawat.getValueAt(tbPesawat.getSelectedRow(), 1).toString());
        penerbanganform.setMaskapai(tbPesawat.getValueAt(tbPesawat.getSelectedRow(), 2).toString());
        penerbanganform.itemTerpilihPesawat();
        this.dispose();

    }//GEN-LAST:event_tbPesawatMouseClicked

    private void btPesawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesawatActionPerformed
        new PesawatForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_btPesawatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CariPesawatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CariPesawatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CariPesawatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CariPesawatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CariPesawatForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTkeluar;
    private javax.swing.JButton btPesawat;
    private javax.swing.JTextField cariTF;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbPesawat;
    // End of variables declaration//GEN-END:variables
}
