/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fahmi.penerbangan.form;

import fahmi.penerbangan.model.Kelas;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fahmi
 */
public class KelasForm extends javax.swing.JFrame {
//    KODING KU
    private String id_penerbangan;
    
//    SEETER
    public void setId_penerbangan(String id_penerbangan) {
        this.id_penerbangan = id_penerbangan;
    }
    

//    KODING KU
    Kelas kelas = new Kelas();
    
    public void tampilData(){
        ArrayList<Kelas> list = kelas.read(id_penerbanganTF.getText());
        
        DefaultTableModel tableModel = (DefaultTableModel) tbKelas.getModel();
        tableModel.setRowCount(0);
        
        Object[] row = new Object[6];
        
        if(list.size() > 0){
//            System.out.println("Jalan");
            for (int i = 0; i<list.size(); i++){
                row[0] = list.get(i).getId_kelas();
                row[1] = list.get(i).getId_penerbangan();
                row[2] = list.get(i).getKelas();
                row[3] = list.get(i).getKursi();
                row[4] = list.get(i).getBagasi();
                row[5] = list.get(i).getHarga();
                
//                KODE OTOMATIS
                String kodeAsli = list.get(i).getId_kelas();
                int kodeAngka =(Integer.parseInt(kodeAsli.substring(0,1))+1);
//                System.out.println(kodeAngka);
                
                id_kelasTF.setText(String.valueOf(kodeAngka+"/"+id_penerbangan));
                tableModel.addRow(row);
            }
        }else if(list.size() == 0){
            id_kelasTF.setText("1/"+id_penerbangan);
        }

    }
    
    public void reset() {
        id_penerbanganTF.setText(id_penerbangan);
        
        id_kelasTF.setEnabled(false);
        kelasTF.setText("");
        kursiTF.setText("");
        bagasiTF.setText("");
        hargaTF.setText("");
        BTtambah.setEnabled(true);
        BTubah.setEnabled(false);
        BThapus.setEnabled(false);
        tampilData();
      }
    
    
    /**
     * Creates new form KelasForm
     */
    public KelasForm() {
        initComponents();
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        id_kelasTF = new javax.swing.JTextField();
        kelasTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        kursiTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bagasiTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        hargaTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        id_penerbanganTF = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        BTtambah = new javax.swing.JButton();
        BTbersih = new javax.swing.JButton();
        BThapus = new javax.swing.JButton();
        BTkeluar = new javax.swing.JButton();
        BTubah = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbKelas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel3.setText("Id Kelas");

        jLabel4.setText("Kelas");

        jLabel6.setText("kursi");

        jLabel7.setText("Bagasi");

        jLabel8.setText("Harga");

        jLabel1.setText("Id Penerbangan");

        id_penerbanganTF.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hargaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(bagasiTF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kursiTF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kelasTF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(id_penerbanganTF)
                            .addComponent(id_kelasTF, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id_penerbanganTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(id_kelasTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(kelasTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(kursiTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(bagasiTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(hargaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        BTtambah.setText("Tambah");
        BTtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTtambahActionPerformed(evt);
            }
        });

        BTbersih.setText("Bersih");
        BTbersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTbersihActionPerformed(evt);
            }
        });

        BThapus.setText("Hapus");
        BThapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BThapusActionPerformed(evt);
            }
        });

        BTkeluar.setText("Keluar");
        BTkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTkeluarActionPerformed(evt);
            }
        });

        BTubah.setText("Ubah");
        BTubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTubahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(252, Short.MAX_VALUE)
                .addComponent(BTtambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTubah)
                .addGap(18, 18, 18)
                .addComponent(BTbersih)
                .addGap(18, 18, 18)
                .addComponent(BThapus)
                .addGap(18, 18, 18)
                .addComponent(BTkeluar)
                .addGap(221, 221, 221))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTtambah)
                    .addComponent(BTbersih)
                    .addComponent(BThapus)
                    .addComponent(BTkeluar)
                    .addComponent(BTubah))
                .addContainerGap())
        );

        jLabel9.setText("Daftar Kelas");

        tbKelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Kelas", "ID Penerbangan", "Kelas", "Kursi", "Bagasi", "Harga"
            }
        ));
        tbKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKelasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbKelas);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTtambahActionPerformed
        kelas.setId_kelas(id_kelasTF.getText());
        kelas.setId_penerbangan(id_penerbanganTF.getText());
        kelas.setKelas(kelasTF.getText());
        kelas.setKursi(Integer.parseInt(kursiTF.getText()));
        kelas.setBagasi(Double.parseDouble(bagasiTF.getText()));
        kelas.setHarga(Integer.parseInt(hargaTF.getText()));

        if (kelas.create()){
            tampilData();
            JOptionPane.showMessageDialog(null, "Berhasil Di Simpan");
            reset();
        }else{
            JOptionPane.showMessageDialog(null, "Gagal Di Simpan");
        }
    }//GEN-LAST:event_BTtambahActionPerformed

    private void BTbersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTbersihActionPerformed
        reset();
    }//GEN-LAST:event_BTbersihActionPerformed

    private void BThapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BThapusActionPerformed
                try {
                        int jawab;
            
                        if ((jawab = JOptionPane.showConfirmDialog(null, "Ingin menghapus data?", "konfirmasi", JOptionPane.YES_NO_OPTION)) == 0) {
                                kelas.setId_kelas(id_kelasTF.getText());
                
                                if (kelas.delete()){
                                        tampilData();
                                        JOptionPane.showMessageDialog(null, "Berhasil Di Hapus");
                                        reset();
                                    }else{
                                        JOptionPane.showMessageDialog(null, "Gagal Di Hapus");
                                    }
                
                                tampilData();
                                reset();
                            }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
    }//GEN-LAST:event_BThapusActionPerformed

    private void BTkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTkeluarActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this,
            "Konfirmasi Keluar Aplikasi",
            "Yakin untuk keluar dari program",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_BTkeluarActionPerformed

    private void BTubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTubahActionPerformed
        kelas.setId_kelas(id_kelasTF.getText());
        kelas.setKelas(kelasTF.getText());
        kelas.setKursi(Integer.parseInt(kursiTF.getText()));
        kelas.setBagasi(Double.parseDouble(bagasiTF.getText()));
        kelas.setHarga(Integer.parseInt(hargaTF.getText()));
        

        if (kelas.update()){
            tampilData();
            JOptionPane.showMessageDialog(null, "Berhasil Di Ubah");
            reset();
        }else{
            JOptionPane.showMessageDialog(null, "Gagal Di Ubah");
        }
    }//GEN-LAST:event_BTubahActionPerformed

    private void tbKelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKelasMouseClicked
        id_kelasTF.setText(tbKelas.getValueAt(tbKelas.getSelectedRow(), 0).toString());
        kelasTF.setText(tbKelas.getValueAt(tbKelas.getSelectedRow(), 2).toString());
        kursiTF.setText(tbKelas.getValueAt(tbKelas.getSelectedRow(), 3).toString());
        bagasiTF.setText(tbKelas.getValueAt(tbKelas.getSelectedRow(), 4).toString());
        hargaTF.setText(tbKelas.getValueAt(tbKelas.getSelectedRow(), 5).toString());
        BTtambah.setEnabled(false);
        BTubah.setEnabled(true);
        BThapus.setEnabled(true);
        id_penerbanganTF.setEnabled(false);
    }//GEN-LAST:event_tbKelasMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        reset();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KelasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KelasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KelasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KelasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KelasForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTbersih;
    private javax.swing.JButton BThapus;
    private javax.swing.JButton BTkeluar;
    private javax.swing.JButton BTtambah;
    private javax.swing.JButton BTubah;
    private javax.swing.JTextField bagasiTF;
    private javax.swing.JTextField hargaTF;
    private javax.swing.JTextField id_kelasTF;
    private javax.swing.JTextField id_penerbanganTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kelasTF;
    private javax.swing.JTextField kursiTF;
    private javax.swing.JTable tbKelas;
    // End of variables declaration//GEN-END:variables
}
